//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPID { get; set; }
        public string EMPNAME { get; set; }
        public string EMPDESG { get; set; }
        public Nullable<int> DEPTID { get; set; }
        public Nullable<int> SALARY { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
